name:                category-breadcrumb
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- text
- containers
- servant
- servant-client
- http-client
- http-client-tls
- aeson
- generic-aeson

default-extensions:
- OverloadedStrings

ghc-options:
  - -Wall
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  category-breadcrumb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - category-breadcrumb

tests:
  category-breadcrumb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - category-breadcrumb
    - hspec
    - hspec-discover
    - QuickCheck
    - hspec-wai
    - hspec-wai-json


verbatim:
  cabal-version: 3.0